### ISSUE TITLE
 infinispan-cli-14.0.0.Dev01-windows-amd64.zip doesnt contain any binary files

### ISSUE THREAD

**Issue by agilob** [infinispan/infinispan-quarkus#88]
The release package contains only readme and licence files

**Comment by ryanemerson** [comment]
Thanks for raising the issue @agilob. We're looking into this at the minute. Frustratingly, the binary files are created when we build on a local windows machine but not when we build via GitHub actions. Our release script is executed via GitHub actions which is why the file is missing from the .zip.
